### ISSUE TITLE
Native SDKs support: allow google/facebook/apple native SDKs

### ISSUE THREAD

**Issue by danielgomezrico** [mishatron/flutter_auth0#14]
As I understand, this implementation shows a Webview and do each social login or authentication from there, so I was wondering:

1. Is this true?
2. If so, is there any reason to have it like that and not be able to run native authentication?

**Comment by mishatron** [comment]
The library supports authentication with password, OTP, and so on (look at the readme file). And all these methods call auth0 API. So it does not show any Webview, it is native authentication.

**Comment by danielgomezrico** [comment]
So for example, if the user tries to log in with Facebook or google it will work natively without showing a web view on top?

**Comment by mishatron** [comment]
As you can see, the library doesn`t support facebook and so on.  It supports auth with password, OTP etc.

**Comment by danielgomezrico** [comment]
Oh got it

Is there any reason for that? or you are waiting for someone to maybe add the feature?

thanks

**Comment by mishatron** [comment]
Previously there was no need to do such a feature, and no ability to do it. As I know, Auth0 wants to provide its official library soon. So if you wish you could wait or provide PR for my library
