### ISSUE TITLE
support "passwordless" via email as well as SMS

### ISSUE THREAD

**Issue by maks** [mishatron/flutter_auth0#6]
Auth0 supports ["passwordless" logins via email](https://auth0.com/docs/connections/passwordless/implement-login/embedded-login/relevant-api-endpoints) (using OTP codes and magic-links) as well as via sms, so it would be great to support that with this very nice library.

I'll submit a small PR shortly that adds support to allow using email.

**Comment by mishatron** [comment]
@maks Thanks for contributing to this package. I released a new beta version because I updated dio to beta-version

**Comment by maks** [comment]
@mishatron awesome, thank you so much for looking at this, merging the PR an doing a new beta release so quickly! 👍🏻
